name: Mirror Upstream

on:
  schedule:
    - cron: '0 * * * *'   # Every hour
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_PAT }}

      - name: Mirror upstream
        run: |
          git remote add upstream https://github.com/ProjectIgnis/bin.git

          git fetch upstream

          git checkout master
          git reset --hard upstream/master

          git push --force origin master