name: Scheduled Upstream Sync

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to manually trigger the sync if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_sync_branch: master      # Change to 'master' if your default branch is different
          upstream_sync_repo: ProjectIgnis/bin # Change to the 'username/repo_name' of the original project
          upstream_sync_branch: master    # Change to the upstream branch you want to pull from
